server:
  port: 19999
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: magic-monitor
  profiles:
    active: ${ACTIVE_PROFILES:dev}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


feign:
  httpclient:
    connection-timeout: 6000
ribbon:
  ReadTimeout: 16000